server:
  port: 8081
spring:
  mysql-datasource:
    jdbc-url: jdbc:mysql://localhost:3306/db1
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  postgres-datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/db2
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

# it will not work because I configured my own LocalContainerEntityManagerFactoryBean
# https://stackoverflow.com/questions/28275448/multiple-data-source-and-schema-creation-in-spring-boot
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect